### ISSUE TITLE
Saving of the project take long time. 

### ISSUE THREAD

**Issue by dronecz** [arduino/arduino-ide#1119]
### Describe the problem

When I try to save my project, either by CTRL+S  or File -> Save, it takes more than 20 seconds to save it. 

### To reproduce

I can not provide steps to reproduce it. I did not find out what is triggeering this issue. 

### Expected behavior

It should save immediately. 

### Arduino IDE version

2.0.0-rc8 ; Date: 2022-06-23T09:36:07.533Z ; CLI Version: 0.24.0 [c1b10f56]

### Operating system

Windows

### Operating system version

10 x64 19044.1766

### Additional context

Here is part of the log from %appdata%/Roaming\Arduino IDE:

```
2022-06-27 14:30:51 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:30:54 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:30:56 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:30:58 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:00 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:03 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:05 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:07 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:09 daemon INFO {"level":"info","msg":"Searching tools required for board esp32:esp32:esp32","time":"2022-06-27T14:31:09+02:00"}

2022-06-27 14:31:09 daemon INFO {"dir":"C:\\Program Files (x86)\\Arduino\\libraries","level":"info","location":"ide","msg":"Adding libraries dir","time":"2022-06-27T14:31:09+02:00"}

2022-06-27 14:31:09 daemon INFO {"dir":"C:\\Users\\zuzelka.JIC-BRNO\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\1.0.6\\libraries","level":"info","location":"platform","msg":"Adding libraries dir","time":"2022-06-27T14:31:09+02:00"}

2022-06-27 14:31:09 daemon INFO {"dir":"c:\\Users\\zuzelka.JIC-BRNO\\ownCloud\\@Arduino\\Arduino\\libraries","level":"info","location":"user","msg":"Adding libraries dir","time":"2022-06-27T14:31:09+02:00"}

2022-06-27 14:31:09 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:12 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:14 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:17 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///C:/Users/zuzelka.JIC-BRNO/AppData/Local/Programs/Arduino%20IDE/resources/app/lib/bundle.js:2:6689167
2022-06-27 14:31:18 root INFO isTemp?
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Thanks for your report @dronecz.

What is the path you are saving the sketch to when this problem occurs?

Does the problem occur consistently, or intermittently?

This looks interesting:

> ```text
> 2022-06-27 14:31:09 daemon INFO {"dir":"c:\\Users\\zuzelka.JIC-BRNO\\ownCloud\\@Arduino\\Arduino\\libraries","level":"info","location":"user","msg":"Adding libraries dir","time":"2022-06-27T14:31:09+02:00"}
> ```

Is there something special about the referenced path?:

```text
c:\Users\zuzelka.JIC-BRNO\ownCloud\@Arduino\Arduino\libraries
```

**Comment by dronecz** [comment]
Path for project is in %userprofile%/Documnets/Github/"project folder". Problem occur for me consistently. 

> Is there something special about the referenced path?:

This is just owncloud shared folder so it should not be. I´m using same path for Arduino v 1.x.x.x and there is no problem with it. I test saving with RC7 and there is no issue.

**Comment by dronecz** [comment]
Then saving works at it should.

**Comment by per1234** [comment]
Great, now the important thing is to determine what is the relevant difference between `C:\MySketch` and `%userprofile%/Documnets/Github/"project folder"`

Other than being your user profile folder, is `%userprofile%` special in any way? For example, is it on any sort of a network share drive?

**Comment by dronecz** [comment]
No, it is local user folder in company laptop connected to active directory. Maybe problem is with .JIC-BRNO, which is AD name.

**Comment by robonxt-ai** [comment]
A idea: was OwnCloud running when you tried to save the sketch @dronecz ? It could be possible that OwnCloud "locked" the file when syncing, and the IDE was waiting for it to be ready
