### ISSUE TITLE
Not working on Kubuntu 19.04 (go offline)

### ISSUE THREAD

**Issue by ricardojlrufino** [arduino/arduino-ide#117]
**Describe the bug**
After opening an IDE, it soon appears as OffLine in the status bar
After that, no menu works. Nor the Open

**Screenshots**
![image](https://user-images.githubusercontent.com/515675/81462687-bb2ca100-918a-11ea-86cd-0fd0a02b8bba.png)

**Desktop (please complete the following information):**
 - OS: Kubtunu 19.04
 - Version v0.0.6-alpha.preview

**Additional context**
Console error
```
root INFO Changed application state from 'initialized_layout' to 'ready'.
daemon INFO current best: arduino:avr@1.8.2 [bundle: false, managed: true, version: 1.8.2]
daemon INFO current best: arduino:sam@1.6.11 [bundle: false, managed: true, version: 1.6.11]
daemon INFO current best: digistump:avr@1.6.7 [bundle: false, managed: true, version: 1.6.7]
daemon INFO current best: esp8266:esp8266@2.4.1 [bundle: false, managed: true, version: 2.4.1]
daemon INFO current best: Cosa:avr@1.2.0 [bundle: false, managed: true, version: 1.2.0]
daemon INFO current best: esp32:esp32@1.0.4 [bundle: false, managed: true, version: 1.0.4]
daemon INFO current best: Cosa:avr@1.2.0 [bundle: false, managed: true, version: 1.2.0]
daemon INFO current best: esp32:esp32@1.0.4 [bundle: false, managed: true, version: 1.0.4]
daemon INFO current best: arduino:avr@1.8.2 [bundle: false, managed: true, version: 1.8.2]
daemon INFO current best: arduino:sam@1.6.11 [bundle: false, managed: true, version: 1.6.11]
daemon INFO current best: digistump:avr@1.6.7 [bundle: false, managed: true, version: 1.6.7]
daemon INFO current best: esp8266:esp8266@2.4.1 [bundle: false, managed: true, version: 2.4.1]
root INFO Index has been updated.
daemon INFO panic: runtime error: invalid memory address or nil pointer dereference
daemon INFO [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b926c]
daemon INFO goroutine 15 [running]:
daemon INFO go.bug.st/relaxed-semver.(*Version).CompareTo(0xc0020e2630, 0x0, 0xc00149e8c0)
daemon INFO     /github/home/go/pkg/mod/go.bug.st/relaxed-semver@v0.0.0-20190922224835-391e10178d18/version.go:115 +0x3c
daemon INFO go.bug.st/relaxed-semver.(*Version).GreaterThan(...)
daemon INFO     /github/home/go/pkg/mod/go.bug.st/relaxed-semver@v0.0.0-20190922224835-391e10178d18/version.go:202
daemon INFO github.com/arduino/arduino-cli/arduino/libraries/librariesindex.(*Index).FindLibraryUpdate(0xc00000e008, 0xc000488360, 0x0)
daemon INFO     /__w/arduino-cli/arduino-cli/arduino/libraries/librariesindex/index.go:121 +0x88
daemon INFO github.com/arduino/arduino-cli/commands/lib.listLibraries(0xc002e80340, 0xc000170000, 0x1, 0xc0000b2178, 0x1)
daemon INFO     /__w/arduino-cli/arduino-cli/commands/lib/list.go:65 +0xe8
daemon INFO github.com/arduino/arduino-cli/commands/lib.LibraryList(0xe0f800, 0xc001d94480, 0xc001d944b0, 0xcc4700, 0xc0004f8300, 0xe1dd40)
daemon INFO     /__w/arduino-cli/arduino-cli/commands/lib/list.go:38 +0xb5
daemon INFO github.com/arduino/arduino-cli/commands/daemon.(*ArduinoCoreServerImpl).LibraryList(0xc0001b0f60, 0xe0f800, 0xc001d94480, 0xc001d944b0, 0xc0001b0f60, 0xc001d94480, 0xc00009fb30)
daemon INFO     /__w/arduino-cli/arduino-cli/commands/daemon/daemon.go:288 +0x3f
daemon INFO github.com/arduino/arduino-cli/rpc/commands._ArduinoCore_LibraryList_Handler(0xcc4700, 0xc0001b0f60, 0xe0f800, 0xc001d94480, 0xc0004f8300, 0x0, 0xe0f800, 0xc001d94480, 0xc000617240, 0x4)
daemon INFO     /__w/arduino-cli/arduino-cli/rpc/commands/commands.pb.go:1799 +0x217
daemon INFO google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ae900, 0xe17e40, 0xc000001800, 0xc00112fe00, 0xc0001b3e90, 0x135ea90, 0x0, 0x0, 0x0)
daemon INFO     /github/home/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x4f4
daemon INFO google.golang.org/grpc.(*Server).handleStream(0xc0000ae900, 0xe17e40, 0xc000001800, 0xc00112fe00, 0x0)
daemon INFO     /github/home/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xd97
daemon INFO google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036100, 0xc0000ae900, 0xe17e40, 0xc000001800, 0xc00112fe00)
daemon INFO     /github/home/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xbb
daemon INFO created by google.golang.org/grpc.(*Server).serveStreams.func1
daemon INFO     /github/home/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa1
```

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-cli/pull/1189. Thanks to @r10r and silvanocerza for the fix!
