### ISSUE TITLE
Network issue and configuration

### ISSUE THREAD

**Issue by fpistm** [arduino/arduino-ide#1438]
### Describe the problem

Hi,

I've installed the new official release 2.0.0 (on Windows 10 and Linux Ubuntu 22.04 LTS) from archive.

When launching it, I got this windows and nothing happen.
![image](https://user-images.githubusercontent.com/20641798/190361780-4f34e292-9f61-48bc-8221-1e8d08456889.png)

## First step:
Log from the console are (Linux):

> Starting backend process. PID: 667034
[667055:0915/102131.293101:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Using browser-only version of superagent in non-browser environment
Configuring to accept webviews on '^.+\.webview\..+$' hostname.
root INFO Configuration directory URI: 'file:///local/home/<username>/.theia'
root INFO Backend Object.initialize: 7.5 ms [Finished 1.253 s after backend start]
root INFO Backend Object.configure: 5.8 ms [Finished 1.253 s after backend start]
root INFO Backend MessagingContribution.onStart: 2.9 ms [Finished 1.253 s after backend start]
root INFO Backend OSBackendApplicationContribution.configure: 0.7 ms [Finished 1.320 s after backend start]
root INFO Backend DefaultWorkspaceServer.onStart: 0.6 ms [Finished 1.320 s after backend start]
root INFO Backend LocalizationBackendContribution.configure: 0.4 ms [Finished 1.321 s after backend start]
root WARN Backend LocalizationBackendContribution.initialize took longer than the expected maximum 50 milliseconds: 67.7 ms [Finished 1.321 s after backend start]
root INFO Backend TaskBackendApplicationContribution.onStart: 0.6 ms [Finished 1.321 s after backend start]
root INFO Backend ElectronTokenBackendContribution.configure: 1.7 ms [Finished 1.323 s after backend start]
root INFO Backend PluginDeployerContribution.initialize: 0.8 ms [Finished 1.323 s after backend start]
root INFO Backend ConfigServiceImpl.onStart: 1.4 ms [Finished 1.325 s after backend start]
root INFO Backend WebviewBackendSecurityWarnings.initialize: 0.7 ms [Finished 1.326 s after backend start]
root INFO Backend ArduinoDaemonImpl.onStart: 1.6 ms [Finished 1.327 s after backend start]
root INFO Backend NodeFileUploadService.configure: 3.0 ms [Finished 1.328 s after backend start]
daemon INFO Starting daemon from /local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/arduino-ide-extension/build/arduino-cli...
discovery-log INFO start
discovery-log INFO start new deferred
root INFO Backend BoardDiscovery.onStart: 1.6 ms [Finished 1.330 s after backend start]
root INFO Backend FileDownloadEndpoint.configure: 0.8 ms [Finished 1.330 s after backend start]
root INFO Backend AuthenticationServiceImpl.onStart: 0.6 ms [Finished 1.332 s after backend start]
root INFO Backend PluginApiContribution.configure: 0.7 ms [Finished 1.332 s after backend start]
root INFO Backend HostedPluginReader.configure: 0.4 ms [Finished 1.333 s after backend start]
root INFO Backend HostedPluginReader.configure: 0.1 ms [Finished 1.334 s after backend start]
root INFO Backend PlotterBackendContribution.configure: 0.5 ms [Finished 1.334 s after backend start]
root INFO Theia app listening on http://localhost:40205.
root INFO Finished starting backend application: 5.5 ms [Finished 1.338 s after backend start]
root WARN The local plugin referenced by local-dir:/local/home/<username>/.arduinoIDE/plugins does not exist.
root WARN The local plugin referenced by local-dir:/local/home/<username>/.arduinoIDE/extensions does not exist.
root WARN The local plugin referenced by local-dir:/local/home/<username>/.arduinoProIDE/plugins does not exist.
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "cortex-debug" to a VS Code extension "cortex-debug@0.3.10" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-arduino-tools" to a VS Code extension "vscode-arduino-tools@0.0.2-beta.5" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-builtin-cpp" to a VS Code extension "cpp@1.52.1" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-builtin-json" to a VS Code extension "json@1.46.1" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-builtin-json-language-features" to a VS Code extension "json-language-features@1.46.1" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-cs" to a VS Code extension "vscode-language-pack-cs@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-de" to a VS Code extension "vscode-language-pack-de@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-es" to a VS Code extension "vscode-language-pack-es@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-fr" to a VS Code extension "vscode-language-pack-fr@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-it" to a VS Code extension "vscode-language-pack-it@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-ja" to a VS Code extension "vscode-language-pack-ja@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-nl" to a VS Code extension "vscode-language-pack-nl@1.48.3" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-pt-BR" to a VS Code extension "vscode-language-pack-pt-BR@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-ru" to a VS Code extension "vscode-language-pack-ru@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-tr" to a VS Code extension "vscode-language-pack-tr@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-zh-hans" to a VS Code extension "vscode-language-pack-zh-hans@1.69.0" with engines:
daemon INFO {"level":"info","msg":"Using config file: /local/home/<username>/.arduinoIDE/arduino-cli.yaml","time":"2022-09-15T10:21:32+02:00"}
{"level":"info","msg":"arduino-cli version 0.27.1","time":"2022-09-15T10:21:32+02:00"}
{"level":"info","msg":"Executing `arduino-cli daemon`","time":"2022-09-15T10:21:32+02:00"}
{"IP":"127.0.0.1","Port":"46627"}
daemon INFO Daemon is running.
root INFO ---- DURATION: loadCliConfig took 74.283 ms. Args: [] ----
root INFO Resolve plugins list: 94.7 ms [Finished 1.425 s after backend start]
root INFO Deployed backend plugin "cortex-debug@0.3.10" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/cortex-debug/extension/dist/extension": 7.1 ms [Finished 1.433 s after backend start]
root INFO Deployed backend plugin "vscode-arduino-tools@0.0.2-beta.5" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-arduino-tools/extension/dist/bundle": 5.9 ms [Finished 1.439 s after backend start]
root INFO Deployed backend plugin "cpp@1.52.1" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-builtin-cpp/extension": 13.0 ms [Finished 1.452 s after backend start]
root INFO Deployed backend plugin "json@1.46.1" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-builtin-json/extension": 2.0 ms [Finished 1.454 s after backend start]
root INFO Deployed backend plugin "json-language-features@1.46.1" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-builtin-json-language-features/extension/client/dist/jsonMain": 0.6 ms [Finished 1.455 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-cs@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-cs/extension": 155.6 ms [Finished 1.610 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-de@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-de/extension": 91.1 ms [Finished 1.701 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-es@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-es/extension": 141.6 ms [Finished 1.843 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-fr@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-fr/extension": 109.3 ms [Finished 1.952 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-it@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-it/extension": 81.1 ms [Finished 2.033 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-ja@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-ja/extension": 102.3 ms [Finished 2.136 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-nl@1.48.3" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-nl/extension": 25.9 ms [Finished 2.162 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-pt-BR@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-pt-BR/extension": 129.5 ms [Finished 2.291 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-ru@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-ru/extension": 118.1 ms [Finished 2.409 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-tr@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-tr/extension": 83.8 ms [Finished 2.493 s after backend start]
root INFO Deployed backend plugin "vscode-language-pack-zh-hans@1.69.0" from "/local/data/ide/arduino/arduino_2.0.0/resources/app/plugins/vscode-language-pack-zh-hans/extension": 80.4 ms [Finished 2.574 s after backend start]
root INFO Deploy plugins list: 94.7 ms [Finished 2.582 s after backend start]
root WARN Frontend s.configure took longer than the expected maximum 100 milliseconds: 201.9 ms [Finished 2.584 s after frontend start]
root WARN Frontend keybindings.onStart took longer than the expected maximum 100 milliseconds: 114.1 ms [Finished 2.743 s after frontend start]
root WARN Frontend C.onStart took longer than the expected maximum 100 milliseconds: 161.7 ms [Finished 3.011 s after frontend start]
root ERROR E Failed to connect to localhost:46627 through proxy <address>:<port> with status 403
root ERROR Uncaught Exception: 
root ERROR Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

Same issue on Windows.

It seems the IDE can't connect due to the http_proxy settings (`http_proxy` and `https_proxy` set as an env variables) anyway, user should be warned an issue occurs.

## Second step:
After removing the `http_proxy` and `https_proxy`, the log show it can go further anyway it fails later when other network access are performed.
Here the logs (Linux):

> Starting backend process. PID: 669267
[669288:0915/110646.964823:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Using browser-only version of superagent in non-browser environment
Configuring to accept webviews on '^.+\.webview\..+$' hostname.
root INFO Configuration directory URI: 'file:///local/home/<username>/.theia'
root INFO Backend Object.initialize: 7.4 ms [Finished 1.227 s after backend start]
root INFO Backend Object.configure: 5.7 ms [Finished 1.227 s after backend start]
root INFO Backend MessagingContribution.onStart: 2.9 ms [Finished 1.227 s after backend start]
root INFO Backend OSBackendApplicationContribution.configure: 0.7 ms [Finished 1.293 s after backend start]
root INFO Backend DefaultWorkspaceServer.onStart: 0.6 ms [Finished 1.293 s after backend start]
root INFO Backend LocalizationBackendContribution.configure: 0.3 ms [Finished 1.294 s after backend start]
root WARN Backend LocalizationBackendContribution.initialize took longer than the expected maximum 50 milliseconds: 66.3 ms [Finished 1.294 s after backend start]
root INFO Backend TaskBackendApplicationContribution.onStart: 0.5 ms [Finished 1.294 s after backend start]
root INFO Backend ElectronTokenBackendContribution.configure: 1.7 ms [Finished 1.296 s after backend start]
root INFO Backend PluginDeployerContribution.initialize: 0.8 ms [Finished 1.297 s after backend start]
root INFO Backend ConfigServiceImpl.onStart: 1.4 ms [Finished 1.298 s after backend start]
root INFO Backend WebviewBackendSecurityWarnings.initialize: 0.7 ms [Finished 1.299 s after backend start]
root INFO Backend ArduinoDaemonImpl.onStart: 1.6 ms [Finished 1.300 s after backend start]
root INFO Backend NodeFileUploadService.configure: 2.9 ms [Finished 1.301 s after backend start]
daemon INFO Starting daemon from /local/data/ide/arduino/arduino_2.0.0/resources/app/node_modules/arduino-ide-extension/build/arduino-cli...
discovery-log INFO start
discovery-log INFO start new deferred
root INFO Backend BoardDiscovery.onStart: 1.5 ms [Finished 1.303 s after backend start]
root INFO Backend FileDownloadEndpoint.configure: 0.8 ms [Finished 1.303 s after backend start]
root INFO Backend AuthenticationServiceImpl.onStart: 0.7 ms [Finished 1.305 s after backend start]
root INFO Backend PluginApiContribution.configure: 0.8 ms [Finished 1.305 s after backend start]
root INFO Backend HostedPluginReader.configure: 0.4 ms [Finished 1.306 s after backend start]
root INFO Backend HostedPluginReader.configure: 0.2 ms [Finished 1.306 s after backend start]
root INFO Backend PlotterBackendContribution.configure: 0.5 ms [Finished 1.307 s after backend start]
root INFO Theia app listening on http://localhost:35383.
root INFO Finished starting backend application: 5.4 ms [Finished 1.311 s after backend start]
root WARN The local plugin referenced by local-dir:/local/home/<username>/.arduinoIDE/plugins does not exist.
root WARN The local plugin referenced by local-dir:/local/home/<username>/.arduinoIDE/extensions does not exist.
root WARN The local plugin referenced by local-dir:/local/home/<username>/.arduinoProIDE/plugins does not exist.
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "cortex-debug" to a VS Code extension "cortex-debug@0.3.10" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-arduino-tools" to a VS Code extension "vscode-arduino-tools@0.0.2-beta.5" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-builtin-cpp" to a VS Code extension "cpp@1.52.1" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-builtin-json" to a VS Code extension "json@1.46.1" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-builtin-json-language-features" to a VS Code extension "json-language-features@1.46.1" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-cs" to a VS Code extension "vscode-language-pack-cs@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-de" to a VS Code extension "vscode-language-pack-de@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-es" to a VS Code extension "vscode-language-pack-es@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-fr" to a VS Code extension "vscode-language-pack-fr@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-it" to a VS Code extension "vscode-language-pack-it@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-ja" to a VS Code extension "vscode-language-pack-ja@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-nl" to a VS Code extension "vscode-language-pack-nl@1.48.3" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-pt-BR" to a VS Code extension "vscode-language-pack-pt-BR@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-ru" to a VS Code extension "vscode-language-pack-ru@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-tr" to a VS Code extension "vscode-language-pack-tr@1.69.0" with engines:
root INFO PluginTheiaDirectoryHandler: accepting plugin with path
root INFO Resolved "vscode-language-pack-zh-hans" to a VS Code extension "vscode-language-pack-zh-hans@1.69.0" with engines:
daemon INFO {"level":"info","msg":"Using config file: /local/home/<username>/.arduinoIDE/arduino-cli.yaml","time":"2022-09-15T11:06:48+02:00"}
{"level":"info","msg":"arduino-cli version 0.27.1","time":"2022-09-15T11:06:48+02:00"}
{"level":"info","msg":"Executing `arduino-cli daemon`","time":"2022-09-15T11:06:48+02:00"}
{"IP":"127.0.0.1","Port":"36433"}
daemon INFO Daemon is running.
root INFO ---- DURATION: loadCliConfig took 69.967 ms. Args: [] ----
daemon INFO {"level":"info","msg":"Loading hardware from: /local/home/<username>/.arduino15/packages","time":"2022-09-15T11:06:48+02:00"}
daemon INFO {"index":"/local/home/<username>/.arduino15/library_index.json","level":"info","msg":"Loading libraries index file","time":"2022-09-15T11:06:48+02:00"}
{"dir":"/local/home/<username>/.arduino15/libraries","level":"info","location":"ide","msg":"Adding libraries dir","time":"2022-09-15T11:06:48+02:00"}
{"dir":"/local/home/<username>/Arduino/libraries","level":"info","location":"user","msg":"Adding libraries dir","time":"2022-09-15T11:06:48+02:00"}
root ERROR Detected an error response during the gRPC core client initialization: code: 9, message: Loading index file: loading json index file /local/home/<username>/.arduino15/package_index.json: open /local/home/<username>/.arduino15/package_index.json: no such file or directory
root ERROR Detected an error response during the gRPC core client initialization: code: 9, message: Error loading hardware platform: discovery builtin:serial-discovery not found
root ERROR Detected an error response during the gRPC core client initialization: code: 9, message: Error loading hardware platform: discovery builtin:mdns-discovery not found
root ERROR Detected an error response during the gRPC core client initialization: code: 9, message: Loading index file: reading library_index.json: open /local/home/<username>/.arduino15/library_index.json: no such file or directory
root ERROR The primary packages indexes are missing. Running indexes update before initializing the core gRPC client
daemon INFO {"level":"info","msg":"Updating libraries index","time":"2022-09-15T11:06:48+02:00"}
{"level":"info","msg":"URL: https://downloads.arduino.cc/packages/package_index.tar.bz2","time":"2022-09-15T11:06:48+02:00"}
{"level":"info","msg":"Updating index","time":"2022-09-15T11:06:48+02:00","url":{"Scheme":"https","Opaque":"","User":null,"Host":"downloads.arduino.cc","Path":"/packages/package_index.tar.bz2","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":"","RawFragment":""}}

## Step 3:
So I've added manually the proxy setting in the newly created config `~/.arduinoIDE/arduino-cli.yaml` (linux)
```
network:
  proxy: http://<username>:<password>@<proxy>:<port>
```
Finally I was able to get the IDE properly started.

### To reproduce

Works behind a proxy.

### Expected behavior

- Warn user properly instead of having empty windows with 'splashscreen' or proposed to configure network proxy.
- Document proxy settings requirements for Arduino IDE 2.0.0

Maybe partially linked to #29

### Arduino IDE version

2.0.0

### Operating system

Windows, Linux

### Operating system version

Windows10 and Linux ubuntu 22.04 LTS

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
TODOs on the IDE2 side:
 - [ ] Search for a JS lib to detect the system proxy configuration. The candidate is [`os-proxy-config`](https://www.npmjs.com/package/os-proxy-config) from [HTTP Toolkit](https://github.com/httptoolkit).
 - [ ] The core gRPC client initialization must be resilient. Even on a fatal error, the IDE2 should open.
 - [ ] IDE2 must start even if no platforms/libs were downloaded the very first time IDE2 starts. It's OK if the boards/lib manager is not functional, but the users must be notified when there is no Internet connection or the CLI cannot download anything due to being behind a proxy.
    - Preferably, the proxy configuration should be adjusted from the _Settings_ dialog by users.
    - If the _Settings_ dialog is not functional, IDE2 must open the `~/arduinoIDE/arduino-cli.yaml` configuration file inside IDE2 for editing.

TODOs on the CLI side:
 - [ ] In the long run, `network#proxy#'auto'` should be supported.
 - [ ] Search for a Golang lib that can detect the system proxy configuration.

**Comment by tennessine** [comment]
Same issue on macos Monterey 12.6.3

arduino ide 2.0.4 nightly

**Comment by tennessine** [comment]
Same issue on macos Monterey 12.6.3

arduino ide 2.0.4 nightly

**Comment by Lucius0806** [comment]
What is a proxy server login? <proxy scheme>: the URL scheme for your proxy server.

**Comment by DL7BJ** [comment]
Same issue with Arduino IDE 2.1.0 for Windows.

**Comment by Dmitry-Chernikov** [comment]
Hello, according to the information [from here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file) Proxy Auto-Configuration file is a js script with FindProxyForURL, Node.js function executes this script from the command line. You can get the result of the execution and substitute it automatically into the function that uses the settings:
network:
   proxy: http://<username>:<password>@<proxy>:<port>

**Comment by scls19fr** [comment]
I can't use Arduino 2.x at work (university) with my students until this is fixed.
I really hope to see soon a fix about it!

**Comment by fpistm** [comment]
> I can't use Arduino 2.x at work (university) with my students until this is fixed. I really hope to see soon a fix about it!

With the workaround, it should works even if it is not user friendly.

One thing we noticed is we update the IDE thanks the update notification, the network configuration set in the arduino-cli.yaml is not preserved.
