### ISSUE TITLE
Clicking left icons produces react error

### ISSUE THREAD

**Issue by SuperNinja-4965** [arduino/arduino-ide#1585]
### Describe the problem

clicking left icons produces the following error in the log. Usually happens on the debug icon. 
```
root ERROR Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Xa (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9401735)
    at Object.enqueueForceUpdate (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9360805)
    at t.y.forceUpdate (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9765129)
    at t.value (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9590266)
    at t.value (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9598479)
    at t.value (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9592148)
    at aa (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9394904)
    at bl (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9412431)
    at t.unstable_runWithPriority (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9786028)
    at Go (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9356534)
```

### To reproduce

Doesnt always happen. only about 80% of the time

### Expected behavior

No error

### Arduino IDE version

2.0.1

### Operating system

Linux

### Operating system version

Arch Linux

### Additional context

Full Log: https://gist.github.com/joshuag1000/47556f393bab370db0af7f2293c29185

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
There are two issues.

> Full Log: https://gist.github.com/joshuag1000/47556f393bab370db0af7f2293c29185

From ☝️:

```
root ERROR [hosted-plugin: 34768] ApplicationInsights:CorrelationIdManager [
  Error: connect ECONNREFUSED 0.0.0.0:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 443
  }
]
```

```
root ERROR Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Xa (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9401735)
    at Object.enqueueForceUpdate (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9360805)
    at t.y.forceUpdate (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9765129)
    at t.value (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9590266)
    at t.value (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9598479)
    at t.value (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9592148)
    at aa (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9394904)
    at bl (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9412431)
    at t.unstable_runWithPriority (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9786028)
    at Go (file:///home/a/Downloads/arduino-ide_2.0.1_Linux_64bit/resources/app/lib/bundle.js:2:9356534)
```

This leads [to](https://reactjs.org/docs/error-decoder.html/?invariant=185):

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
