### ISSUE TITLE
Failed to start the electron application

### ISSUE THREAD

**Issue by cnlog** [arduino/arduino-ide#1961]
### Describe the problem

Failed to start the electron application.
Error: EISDIR: illegal operation on a directory, realpath 'G:\Temp\tmp'
    at Function.realpathSync.native (node:fs:2540:3)
    at Function.native (node:electron/js2c/asar_bundle:5:4819)
    at new IsTempSketch (E:\XXX\arduino\resources\app\node_modules\arduino-ide-extension\lib\node\is-temp-sketch.js:25:51)
    at Object.resolveInstance (E:\XXX\arduino\resources\app\node_modules\inversify\lib\resolution\instantiation.js:51:18)
    at E:\XXX\arduino\resources\app\node_modules\inversify\lib\resolution\resolver.js:75:42
    at Array.map (<anonymous>)
    at _injectProperties (E:\XXX\arduino\resources\app\node_modules\inversify\lib\resolution\instantiation.js:17:57)
    at Object.resolveInstance (E:\XXX\arduino\resources\app\node_modules\inversify\lib\resolution\instantiation.js:48:18)
    at E:\XXX\arduino\resources\app\node_modules\inversify\lib\resolution\resolver.js:75:42
    at Object.resolve (E:\XXX\arduino\resources\app\node_modules\inversify\lib\resolution\resolver.js:99:12) {
  errno: -4068,
  syscall: 'realpath',
  code: 'EISDIR',
  path: 'G:\\Temp\\tmp'

### To reproduce

I installed the temporary directory  on the memory disk. so I got that message.

### Expected behavior

I installed the temporary directory  on the memory disk. so I got that message.

### Arduino IDE version

2.02

### Operating system

Windows

### Operating system version

21H2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment]
Thank you for taking the time and writing the bug report. It's a known issue. 😕 IDE2 does not start on a ram drive: https://github.com/arduino/arduino-ide/issues/1236.

We prefer keeping one ticket open for the same problem. Please comment on the other one if you have any additional info on this topic.

I am closing it as a duplicate.
