### ISSUE TITLE
2.3.2 AppImage fails to start due to missing sandboxing

### ISSUE THREAD

**Issue by AndKe** [arduino/arduino-ide#2429]
### Describe the problem

```
./arduino-ide_2.3.2_Linux_64bit.AppImage 
[49662:0505/163801.040968:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_arduinl1RTCc/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

```

### To reproduce

Start .AppImage on Ubuntu 24.04

### Expected behavior

Work as normal.

### Arduino IDE version

2.3.2

### Operating system

Linux

### Operating system version

Ubuntu 24.04

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by mariovaldez** [comment]
The issue is with the AppArmor configuration in Ubuntu 24.04, not the AppImage. The change in the configuration is explained in the release notes of Ubuntu 24.04 (security reasons).

Because this problem is caused by the OS configuration, I'm not use what the Arduino IDE team can do, except for documenting the installation procedure.

You can disable the sandboxing restriction for all program with:
```
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=1
```
or by adding to /etc/sysctl.d/local.conf:
```
kernel.apparmor_restrict_unprivileged_userns=0
```
But that defeats the purpose of the new AppArmor restriction in Ubuntu 24.04.

You can also create a new AppArmor profile for the Arduino IDE (that allows a non-root user to use the sandboxing in a specific application). If you copy the AppImage to /usr/local/bin/arduino (for example), you can create an AppArmor profile with a configuration file, for example, in /etc/apparmor.d/usr.local.bin.arduino, containing:
```
abi <abi/4.0>,
include <tunables/global>
profile arduino /usr/local/bin/arduino flags=(unconfined) {
  userns,
  include if exists <local/arduino>
}
```
and reloading all AppArmor profiles with:
```
sudo service apparmor reload
```
Now you can run the Arduino IDE without the sandboxing error.

You could also run the Arduino IDE with the --no-sandbox option, but that is, in my opinion, a potentially very bad idea.

**Comment by AndKe** [comment]
@mariovaldez Thank you for a good explanation/solution.
Is this going to be easier / fixed in future releases? - so far, I have seen this issue with only two .AppImage applications.

The /usr/local/bin/arduino  you refer to, is that a directory, or is arduino the actual arduino.Appmage?
I have a directory for all my AppImages. it would be tempting to make an AppArmor configuration file for all .AppImage files in that dir.

**Comment by mariovaldez** [comment]
@AndKe I don't think this will change with later versions of Ubuntu. My understanding is that allowing normal users to use kernel namespaces has been considered a security risk (the kernel namespaces are used to create the sandbox in some AppImage applications). The change in the AppArmor configuration of Ubuntu is a mitigation for that risk.

Regarding the "/usr/local/bin/arduino" path, that's the program name I used. You can use any filename you like (for example, "/usr/local/bin/arduino.AppImage"). I used the "/usr/local/bin" directory just to follow the Linux FHS guidelines but you can install the program anywhere you want (I'm sure lot of people prefer to install in /opt, or even in a per-user ~/opt or ~/bin directory).

Currently I'm using some other AppImage applications (ungoogled-chromium, teams-for-linux, upscayl) that also require their own AppArmor profile.

**Comment by AndKe** [comment]
@mariovaldez  Thank you,  sorry for asking a vague question, I did not mean to ask is it will change in future Ubuntu releases, but if the future Arduino IDE  AppImage releases will require this fix in forseeable future. Or if some changes to the IDE will make this issue be a thing of the past.

**Comment by mariovaldez** [comment]
@AndKe The Arduino IDE 2 is really a Typescript/Javascript web application running locally with a Chromium engine (as an Electron app, in this case all packaged in an AppImage).

The Chromium engine uses the sandboxing to reduce security risks. There are several ways to implement the sandboxing. On Linux, the Chromium engine currently uses unprivileged kernel  namespaces (in the past other ways have been used but I think they are deprecated now). 

So, as long as the Arduino IDE uses the Chromium engine provided by the Electron framework, and as long as the Chromium engine requires unprivileged namespaces for the sandboxing, and as long as Ubuntu (or any other distribution) restricts the use of the namespaces, the apparmor profile is needed.

**Comment by AndKe** [comment]
Yes, unpriviliged is deprecated now, but at least Ubuntu, when *upgraded* to 24.04 is still accepting unprivileged kernel namespaces - while new installations of the same distro enforces this.
This issue will only grow as time goes, also: it is more likely to annoy new Linux users. (due to new installation)

**Comment by eccentricOrange** [comment]
@mariovaldez AFAIK, other applications like VS Code also use the Electron+Chromium+NodeJS combination right? How do they get around this issue? I didn't have to muck around with this when installing VS Code in Ubuntu 24.04

(apologies if I seem ignorant of something, I am not a web developer and do not know about JS/TS-related concepts in depth)

**Comment by eccentricOrange** [comment]
Got it, thanks for the explanation!

**Comment by shaw-a** [comment]
Hi @mariovaldez, all, 

I am using Ubuntu 24.04. I tried to use the AppArmor profile solution,  I like the idea of complying with canonical's security decisions rather than working around them. However after following these steps, I still get the same error as in the original post. 
1. Download arduino-ide_2.3.2_Linux_64bit.AppImage
1. `sudo mkdir /usr/local/bin/arduino && sudo cp ~/Downloads/arduino-ide_2.3.2_Linux_64bit.AppImage /usr/local/bin/arduino/`
2. `chmod +x /usr/local/bin/arduino/arduino-ide_2.3.2_Linux_64bit.AppImage`
3. create /etc/apparmor.d/usr.local.bin.arduino containing:
```
abi <abi/4.0>,
include <tunables/global>
profile arduino /usr/local/bin/arduino flags=(unconfined) {
  userns,
  include if exists <local/arduino>
} 
```
4. reload AppArmor with `sudo service apparmor reload`

Now, when I run `usr/local/bin/arduino/arduino-ide_2.3.2_Linux_64bit.AppImage` I get the error:

>/usr/local/bin/arduino/arduino-ide_2.3.2_Linux_64bit.AppImage 
[5481:0603/171920.702980:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_arduineWT4bK/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)

Funnily enough, I am unable to run `arduino` as a command to launch the AppImage even though I expected to since /usr/local/bin is in my $PATH:
```
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
I'm not sure if this is related to why the solution did not work as expected and I wonder do you have any advice for what to try next.

So far I have tried: 
1. rebooting
2. sudo apt update and sudo apt upgrade, then rebooting
3. setting `PATH=$PATH'
4. double checking all the paths and the contents of the /etc/apparmor.d/usr.local.bin.arduino file
5. downloading the arduino appimage again and repeating the steps

**Comment by shaw-a** [comment]
Hi @mariovaldez,

I really appreciate your response and your explanation. Following this advice the solution works for me as expected and I can launch the arduino IDE from anywhere by typing the command `arduino`. It was a big aha moment when you mentioned that it was the file name. Thanks for explaining more about the symbolic links and AppArmor profile, I will definitely try those out.

Kind regards!

**Comment by zolki** [comment]
Thank you all for the help. My successful set-up with my `/etc/apparmor.d/arduino-ide` file is:
```
abi <abi/4.0>,
include <tunables/global>
profile arduino-ide* /opt/arduino-ide* flags=(unconfined) {
  userns,
  include if exists <local/arduino*>
}
``` 
I set the SUID attribute flag for the `chrome-sandbox` executable, the `4` ahead of `755`, as the message recommended earlier: `4755`, when the app could not run.

My chosen path was `/opt/arduino-ide_2.3.3_Linux_64bit/` of the unzipped software package, containing also the `arduino-ide` executable file.

My desktop entry shortcut file is `arduino-arduinoide.desktop:`
<details><summary>Details</summary>
<p>

[Desktop Entry]
Type=Application
Name=Arduino IDE
GenericName=Arduino IDE
Comment=Open-source electronics prototyping platform
Exec=/opt/arduino-ide_2.3.3_Linux_64bit/arduino-ide
Icon=arduino-arduinoide
Terminal=false
Categories=Development;IDE;Electronics;
MimeType=text/x-arduino;
Keywords=embedded electronics;electronics;avr;microcontroller;
StartupWMClass=processing-app-Base

</p>
</details>

**Comment by martin3000** [comment]
> You could also run the Arduino IDE with the --no-sandbox option, but that is, in my opinion, a potentially very bad idea.

Why should running an appimage without sandboxing be worse than running any other linux binary (without sudo)?

**Comment by truher** [comment]
Finally, *this* is the year of Linux on the desktop!

**Comment by gneiss15** [comment]
I use another aproach: replace the chrome-sandbox binary inside the AppImage whith a link to the version of the local system.
e.g:

> cd squashfs-root/
rm chrome-sandbox
ln -s $(find /opt -name "chrome-sandbox") chrome-sandbox
cd ..

That wors for me (my installation of Ubuntu 24.).
I am not shure if chrome-sandbox is always installed in /opt, if so, it may be possible to do this inside AppRun.

@per1234 : May You look at this ?

**Comment by MaKaNu** [comment]
I came across this issue and just interpreted the error message and updated the permissions to 4755. Got sceptical about that "stickybit" and researched it.

Found an explanation about `sudo chmod 4755` and understand why I have never heard about it before.

Now my question: why does the error point out the stickybit solution and why does the appArmor solution seems to be the better/preferred solution?

**Comment by gneiss15** [comment]
The sticky bit and the owner (root) get's lost when the sqashfs inside the Appimage was extracted.
So a call of the chrom-sandbox (from the Appimage) falls. That's why I suggest the use of the local file

**Comment by Van-too** [comment]
An example of one solution.
Create a text file named **arduino.sh** in the folder with your appimage file.
Write the following in it:
./**arduino-ide_2.3.6_Linux_64bit.AppImage** --no-sandbox
Save it, open the properties of the file arduino.sh, make the file executable, and run it.

**arduino-ide_2.3.6_Linux_64bit.AppImage** is the name of your file; it may be different.

**Comment by hechaotudou** [comment]
sudo  ./arduino-ide_2.3.6_Linux_64bit.AppImage  --no-sandbox
Arduino IDE 2.3.6
Checking for frontend application configuration customizations. Module path: /tmp/.mount_arduin1tFPCu/resources/app/lib/backend/electron-main.js, destination 'package.json': /tmp/.mount_arduin1tFPCu/resources/app/package.json
[12786:0621/044429.782111:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12786:0621/044429.782151:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12786:0621/044429.782159:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12786:0621/044429.782165:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Setting 'theia.frontend.config.appVersion' application configuration value to: "2.3.6" (type of string)
Setting 'theia.frontend.config.cliVersion' application configuration value to: "1.2.0" (type of string)
Setting 'theia.frontend.config.buildDate' application configuration value to: "2025-04-09T11:24:04.835Z" (type of string)
Frontend application configuration after modifications: {"applicationName":"Arduino IDE","defaultTheme":{"light":"arduino-theme","dark":"arduino-theme-dark"},"defaultIconTheme":"none","electron":{"windowOptions":{},"showWindowEarly":true,"splashScreenOptions":{},"uriScheme":"arduino-ide"},"defaultLocale":"","validatePreferencesSchema":false,"reloadOnReconnect":true,"uriScheme":"theia","preferences":{"window.title":"${rootName}${activeEditorShort}${appName}","files.autoSave":"afterDelay","editor.minimap.enabled":false,"editor.tabSize":2,"editor.scrollBeyondLastLine":false,"editor.quickSuggestions":{"other":false,"comments":false,"strings":false},"editor.maxTokenizationLineLength":500,"editor.bracketPairColorization.enabled":false,"breadcrumbs.enabled":false,"workbench.tree.renderIndentGuides":"none","explorer.compactFolders":false},"appVersion":"2.3.6","cliVersion":"1.2.0","buildDate":"2025-04-09T11:24:04.835Z"}
Starting backend process. PID: 12826
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[12819:0621/044430.072806:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12819:0621/044430.072889:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12819:0621/044430.072946:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified

[12819:0621/044430.073013:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12819:0621/044430.073029:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12819:0621/044430.073042:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[12819:0621/044430.073055:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[12819:0621/044430.073069:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[12786:0621/044430.131410:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[12819:0621/044430.166201:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12819:0621/044430.166241:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12819:0621/044430.166256:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified

[12819:0621/044430.166312:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12819:0621/044430.166326:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12819:0621/044430.166338:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[12819:0621/044430.166351:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[12819:0621/044430.166363:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[12819:0621/044430.166990:ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
Showing main window early
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[12851:0621/044430.252069:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12851:0621/044430.252121:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12851:0621/044430.252135:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified

[12851:0621/044430.252183:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12851:0621/044430.252198:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12851:0621/044430.252211:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[12851:0621/044430.252224:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[12851:0621/044430.252238:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[12851:0621/044430.310349:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12851:0621/044430.310393:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12851:0621/044430.310406:ERROR:gl_display.cc(786)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Authorization required, but no authorization protocol specified

[12851:0621/044430.310459:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[12851:0621/044430.310473:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[12851:0621/044430.310486:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[12851:0621/044430.310498:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[12851:0621/044430.310510:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[12851:0621/044430.311179:ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Using browser-only version of superagent in non-browser environment
Configuration directory URI: 'file:///root/.arduinoIDE'
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[12861:0621/044430.375752:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[12861:0621/044430.375798:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[12861:0621/044430.375818:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Not initialized.
[12861:0621/044430.375831:ERROR:gl_display.cc(786)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[12861:0621/044430.375846:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[12861:0621/044430.375860:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
Configuring to accept webviews on '^.+\.webview\..+$' hostname.
Authorization required, but no authorization protocol specified

2025-06-20T20:44:30.410Z root INFO Backend u.initialize: 22.5 ms [Finished 0.456 s after backend start]
2025-06-20T20:44:30.411Z root INFO Backend Object.initialize: 21.6 ms [Finished 0.456 s after backend start]
2025-06-20T20:44:30.411Z root INFO Backend a.initialize: 0.7 ms [Finished 0.456 s after backend start]
2025-06-20T20:44:30.411Z root INFO Backend a.initialize: 0.5 ms [Finished 0.456 s after backend start]
2025-06-20T20:44:30.411Z root INFO Backend u.initialize: 0.7 ms [Finished 0.456 s after backend start]
2025-06-20T20:44:30.412Z root INFO Backend l.initialize: 22.4 ms [Finished 0.457 s after backend start]
2025-06-20T20:44:30.416Z root INFO configured all backend app contributions
2025-06-20T20:44:30.416Z root INFO Backend l.onStart: 0.7 ms [Finished 0.464 s after backend start]
2025-06-20T20:44:30.417Z root INFO Backend d.onStart: 0.1 ms [Finished 0.464 s after backend start]
2025-06-20T20:44:30.417Z root INFO Backend a.onStart: 0.2 ms [Finished 0.464 s after backend start]
2025-06-20T20:44:30.417Z config INFO >>> Initializing CLI configuration...
2025-06-20T20:44:30.417Z root INFO Backend x.onStart: 0.2 ms [Finished 0.464 s after backend start]
2025-06-20T20:44:30.417Z config INFO Loading CLI configuration from /root/.arduinoIDE/arduino-cli.yaml...
2025-06-20T20:44:30.417Z daemon INFO Starting daemon from /tmp/.mount_arduin1tFPCu/resources/app/lib/backend/resources/arduino-cli...
2025-06-20T20:44:30.417Z root INFO Backend w.onStart: 0.2 ms [Finished 0.465 s after backend start]
2025-06-20T20:44:30.417Z discovery-log INFO start
2025-06-20T20:44:30.417Z discovery-log INFO start new deferred
2025-06-20T20:44:30.417Z root INFO Backend v.onStart: 0.1 ms [Finished 0.465 s after backend start]
2025-06-20T20:44:30.417Z root INFO Backend a.onStart: 0.0 ms [Finished 0.465 s after backend start]
2025-06-20T20:44:30.419Z root INFO Theia app listening on http://127.0.0.0:34621.
2025-06-20T20:44:30.419Z root INFO Finished starting backend application: 1.8 ms [Finished 0.467 s after backend start]
2025-06-20T20:44:30.424Z root WARN The local plugin referenced by local-dir:/root/.arduinoIDE/plugins does not exist.
2025-06-20T20:44:30.424Z root WARN The local plugin referenced by local-dir:/root/.arduinoIDE/deployedPlugins does not exist.
2025-06-20T20:44:30.430Z config INFO Loaded CLI configuration: {"board_manager":{"additional_urls":[]}}
2025-06-20T20:44:30.430Z config INFO Loading fallback CLI configuration to get 'directories.data' and 'directories.user'
Authorization required, but no authorization protocol specified

[12861:0621/044430.461951:ERROR:angle_platform_impl.cc(44)] DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:58 (initialize): xcb_connect() failed, error 1
[12861:0621/044430.461995:ERROR:angle_platform_impl.cc(44)] Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:1086 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[12861:0621/044430.462014:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Not initialized.
[12861:0621/044430.462028:ERROR:gl_display.cc(786)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[12861:0621/044430.462042:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[12861:0621/044430.462055:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[12861:0621/044430.462693:ERROR:viz_main_impl.cc(198)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[12879:0621/044430.500942:ERROR:x11_software_bitmap_presenter.cc(144)] XGetWindowAttributes failed for window 50331652
2025-06-20T20:44:30.559Z root INFO Resolve plugins list: 140.9 ms [Finished 0.606 s after backend start]
2025-06-20T20:44:30.627Z daemon INFO time="2025-06-21T04:44:30+08:00" level=info msg="arduino-cli version 1.2.0"
2025-06-20T20:44:30.627Z daemon INFO time="2025-06-21T04:44:30+08:00" level=info msg="Using config file: /root/.arduinoIDE/arduino-cli.yaml"
time="2025-06-21T04:44:30+08:00" level=info msg="Executing `arduino-cli daemon`"
2025-06-20T20:44:30.629Z config INFO Loaded fallback CLI configuration: {"directories":{"user":"/root/Arduino","data":"/root/.arduino15"}}
2025-06-20T20:44:30.629Z config INFO Merged CLI configuration with the fallback: {"directories":{"user":"/root/Arduino","data":"/root/.arduino15"},"board_manager":{"additional_urls":[]}}
2025-06-20T20:44:30.629Z config INFO Loaded the CLI configuration.
2025-06-20T20:44:30.637Z daemon INFO Daemon is now listening on 127.0.0.1:37423
{"IP":"127.0.0.1","Port":"37423"}
2025-06-20T20:44:30.637Z daemon INFO Daemon is running.
2025-06-20T20:44:30.642Z root ERROR Uncaught Exception:  Error: 14 UNAVAILABLE: No connection established. Last error: Error: connect ECONNREFUSED 127.0.0.0:37423
2025-06-20T20:44:30.642Z root ERROR Error: 14 UNAVAILABLE: No connection established. Last error: Error: connect ECONNREFUSED 127.0.0.0:37423
    at t.callErrorFromStatus (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:987037)
    at Object.onReceiveStatus (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:3783461)
    at Object.onReceiveStatus (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:2216666)
    at Object.onReceiveStatus (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:2216111)
    at /tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:4354680
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at s.makeUnaryRequest (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:3782992)
    at s.create (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:3311624)
    at instance (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:102990)
    at new Promise (<anonymous>)
    at y.createClient (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:102967)
    at y.create (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:101875)
    at /tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:100771
    at /tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:6419737
    at s.invoke (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:6419827)
    at a.fire (/tmp/.mount_arduin1tFPCu/resources/app/lib/backend/main.js:2:6421630)
2025-06-20T20:44:30.642Z config INFO Mapped the CLI configuration: {"dataDirUri":"file:///root/.arduino15","sketchDirUri":"file:///root/Arduino","additionalUrls":[],"network":"none","locale":"en"}
2025-06-20T20:44:30.642Z config INFO Validating the CLI configuration...
2025-06-20T20:44:30.644Z config INFO The CLI config is valid.
2025-06-20T20:44:30.644Z config INFO <<< Initialized the CLI configuration.
2025-06-20T20:44:31.101Z root INFO Deploy plugins list: 683.1 ms [Finished 1.148 s after backend start]

**Comment by TimoHelm** [comment]
Tried to reproduce the solution but still getting the mentioned "sandbox" error.

My binary in /usr/local/bin is named arduino,

<img width="479" height="86" alt="Image" src="https://github.com/user-attachments/assets/3591eab8-b260-4fdc-8e65-682e3a5797ee" />

created file in apparmor.d:

<img width="492" height="127" alt="Image" src="https://github.com/user-attachments/assets/3fba8fa2-8b87-4185-8b1f-3bcbf911b8bd" />

reloaded apparmor service but still getting error when I try to run arduino:

<img width="641" height="104" alt="Image" src="https://github.com/user-attachments/assets/b2d7be9c-2308-4e92-a829-49d8b3f9656f" />

Of course I can run the arduino-ide with the `--no-sandbox` option, but I wan´t to avoid this.

What am I missing or where do I make a mistake?
Can anybody help?
