### ISSUE TITLE
No indication of what happened when platform installation fails

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#41]
**To Reproduce**
1. Tools > Boards Manager
1. Try to install Arduino mbed-enabled Boards 1.3.1 (this is a fake release only intended to show a deprecation message, which is intended to fail installation)

When I do this with Arduino IDE 2.0.0 (arduino-pro-ide 0.1.2-nightly.20201021, Windows 10, .zip), it just shows "downloading arduino-beta:mbed@1.3.1" in the output console and there is no indication that the installation failed.

When I do this in the Java IDE (1.8.14 hourly 2020-09-23 10:33, Win 10), I get some nice output that makes it reasonably clear what went wrong:

```
Error downloading http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:181)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:149)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:83)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:105)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:174)
	... 1 more
Caused by: java.io.IOException: Received invalid http status code from server: 404
	at cc.arduino.utils.network.FileDownloader.openConnectionAndFillTheFile(FileDownloader.java:239)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:182)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:129)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:147)
	... 5 more
```
The "Error downloading http://downloads.arduino.cc/cores/ArduinoCore-mbed-nonexistant.tar.bz2" is also shown at the bottom of Boards Manager.

**Desktop (please complete the following information):**
OS: Windows 10
Version: 2.0.0-beta.2-snapshot.f9730ab
CLI Version: 0.16.0 alpha [c977a238]

[ originally reported by @per1234 ]

**Comment by ubidefeo** [comment]
Seems resolved in Beta 4

**Comment by ubidefeo** [comment]
@per1234 
is this in any way addressed by Beta 4?
I have installed ATMegaZero which had the weird `__MACOSX__` folder in it and got a proper error message.
I wonder if this case is also covered

**Comment by per1234** [comment]
Yes! Akos made this wonderful improvement in https://github.com/arduino/arduino-ide/pull/195
