### ISSUE TITLE
Unhandled exception causes loop

### ISSUE THREAD

**Issue by jk-murcia** [arduino/arduino-ide#732]
**Describe the bug**
A process labelled root gets an unexpected exception (root ERROR Error: Connection got disposed.) and then repeats apparently forever.  Stopping the IDE returns normal CPU use.

**To Reproduce**
Unknown, but it happens frequently as I frequently experience CPU over-use and its in all the log files for rc-3

**Expected behavior**
Handle the exception

**Screenshots**
No symptoms in UI

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Version: 20.04

**Additional context**
Example log attached.  

Off-topic observation : I notice the IDE is aware of my TV, which is surprising...  
- New port is available on 10.4.1.13 BRAVIA\ TL._androidtvremote2._tcp.local. at 10.4.1.13
- 
[2022-01-02_log.log](https://github.com/arduino/arduino-ide/files/7798881/2022-01-02_log.log)

**Comment by FastThenLeft** [comment]
I have this same issue! Running Ubuntu 22.04 with IDE rc8. The CPU usage shoots through the roof.

Here's the section of the log file where it starts and then it just keeps printing the same section in the log file forever until I kill the IDE.

2022-06-23 13:24:04 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///tmp/.mount_arduinfquyjl/resources/app/lib/bundle.js:2:6680353
2022-06-23 13:24:08 root ERROR Error: Aborted onWillSaveTextDocument-event after 1750ms
    at file:///tmp/.mount_arduinfquyjl/resources/app/lib/bundle.js:2:6680353
2022-06-23 13:24:10 root INFO isTemp?
2022-06-23 13:24:10 root ERROR Uncaught Exception: 
2022-06-23 13:24:10 root ERROR Error: Connection got disposed.
    at Object.dispose (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at /tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/connection.js:14:41
    at CallbackList.invoke (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at WebSocketMessageReader.fireClose (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:67:19)
    at /tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:24:18
2022-06-23 13:24:10 root ERROR Uncaught Exception: 
2022-06-23 13:24:10 root ERROR Error: Connection got disposed.
    at Object.dispose (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/main.js:904:25)
    at /tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/connection.js:14:41
    at CallbackList.invoke (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at closeHandler (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/main.js:240:26)
    at CallbackList.invoke (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at WebSocketMessageReader.fireClose (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
    at WebSocketMessageReader.fireClose (/tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:67:19)
    at /tmp/.mount_arduinfquyjl/resources/app/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:24:18
