### ISSUE TITLE
`root ERROR Error: ENOENT: no such file or directory, stat 'undefined/'`

### ISSUE THREAD

**Issue by jmarkuna** [arduino/arduino-ide#77]
```
root ERROR Uncaught Exception: 
root ERROR Error: ENOENT: no such file or directory, stat 'undefined/'
    at statSync (fs.js:915:3)
    at Object.fs.statSync (electron/js2c/asar.js:278:27)
    at mkDir (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/node-log-rotate/lib/utils/find-log-path.js:52:17)
    at prepareDir (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/node-log-rotate/lib/utils/find-log-path.js:31:9)
    at Object.default_1 [as default] (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/node-log-rotate/lib/utils/find-log-path.js:8:19)
    at Object.default_1 [as default] (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/node-log-rotate/lib/utils/find-log-file-name.js:5:36)
    at Object.default_1 [as default] (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/node-log-rotate/lib/transport-file.js:15:52)
    at log (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/node-log-rotate/lib/index.js:20:36)
    at Object.<anonymous> (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/src-gen/backend/main.js:11:9)
    at Object.log (/spare/downloads/arduinoProIDE/arduino-pro-ide_0.1.3_Linux_64bit/resources/app/node_modules/@theia/core/lib/common/logger-protocol.js:141:17)
```
I ran arduino-pro-ide. funny thing is I cannot `strace` arduino-pro-ide. System says cannot stat file.
Arduino pro gui comes up but I keep getting errors shown about. I can be root on this system, have tried both root acct and non-root account to run arduino-pro-ide

**Comment by fstasi** [comment]
@per1234 I confirm they are related

**Comment by kittaakos** [comment]
> The `undefined/` in the error message makes me suspect this is related to #394

> @per1234 I confirm they are related

Thank you for checking it!

Can we close this issue in favor of #394? I am happy to move the conversation from here to there if required. Thanks!
